version: 0.2
env:
  secrets-manager:
    REACT_APP_GOOGLE_API_KEY: arn:aws:secretsmanager:ap-northeast-1:607456523830:secret:prod/SushiroHKWaiting/GMapApiKey-IW8jBM
phases:
  install:
    commands:
      - npm install --legacy-peer-deps
  # pre_build:
  #   commands:
  #     - npm run test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist