version: 0.2
env:
  secrets-manager:
    REACT_APP_GOOGLE_API_KEY: arn:aws:secretsmanager:ap-northeast-1:607456523830:secret:prod/SushiroHKWaiting/GMapApiKey-IW8jBM
phases:
  install:
    commands:
      - npm install --legacy-peer-deps
      - dnf install -y xorg-x11-server-Xvfb gtk3-devel nss alsa-lib #cypress linux prerequisites
  pre_build:
    commands:
      - npm run lint
      - npm run jest
      - npm run cypress
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://sushiro-hk-waiting-client --recursive
artifacts:
  files:
    - '**/*'
  base-directory: dist