version: 0.2

phases:
  install:
    commands:
      - npm install --legacy-peer-deps
  # pre_build:
  #   commands:
  #     - npm run test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist